
public enum Packets: UInt8 {
    case 
    LOGIN_REQUEST = 1, 
    LOGIN_RESPONSE,
    CHAR_LIST_REQUEST,
    CHAR_LIST_RESPONSE,
    SERVER_LIST_REQUEST,
    SERVER_LIST_RESPONSE,
    JOIN_SERVER_REQUEST,
    JOIN_SERVER_RESPONSE,
    JOIN_WORLD_REQUEST,
    JOIN_WORLD_RESPONSE,
    CHAR_DATA_RESPONSE,
    INVENTORY_RESPONSE,
    START_MOVING_REQUEST,
    START_MOVING_RESPONSE,
    MOVING_REQUEST,
    MOVING_RESPONSE,
    END_MOVING_REQUEST,
    END_MOVING_RESPONSE,
    CHARS_AROUND_RESPONSE
}